### ISSUE TITLE
Problem getting MWOSD v.1.5 64bit GUI batch file to launch application

### ISSUE THREAD

**Issue by cyntrifical** [ShikOfTheRa/scarab-osd-gui#1]
I'm using a FlyColor Raptor 390 Tower 4-in-1 Flight Controller board with built in OSD, and it was loaded from the factory with mwosd r1.5, and I'm not entirely sure if I can or even how to update it to the latest mwosd, but anyways, I have a 64bit Windows 10 PC, and when I try to load the 64bit mwosd gui windows batch file, the command prompt window opens, but as you can see in the photo I've included, it appears it won't open. I can get the 32bit version of mwosd gui v1.5 to work and read and write to my OSD, but is there a reason why the 64bit one may not work? 
![mwosd v1 5 batch file error 64 bit](https://user-images.githubusercontent.com/30678928/43142183-cec9701c-8f25-11e8-91e5-5eefcc0ec1c3.PNG)

**Comment by ShikOfTheRa** [comment]
Its the same app functionality wise - same code - just complied for 32 or 64 bit.
As to why - no idea. Probably some windows trick to force it! I'd keep using the 32 bit for now.

I have no idea on updating flycolor - I tried to communicate with them a few times but could not get a response.
