### ISSUE TITLE
Enhancement MSP OSD

### ISSUE THREAD

**Issue by SilentZen** [ShikOfTheRa/scarab-osd-gui#10]
Would it be possible to implement MSP OSD https://ardupilot.org/copter/docs/common-msp-osd-overview.html#common-msp-osd-overview So that OSD can be provided with standalone OSD with sensors?

**Comment by ShikOfTheRa** [comment]
Interesting. I have never seen that functionality before, but looking at it I wonder if it would work as it is now if installed iNav MWOSD version. It appears that Ardupilot is emulating iNav
The baud rates would have to match - so if using pre-compiled MWOSD flashing then ardupilot would need to be set to 115k speed.

A quick look at the code indicates it has a lot less support than normal ardupilot MWOSD implementation. I guess this is down to supporting what DJI only support.
I

**Comment by ShikOfTheRa** [comment]
Messages would not currently be displayed. I can look to add this. 
Screen positions would have to be set up in MWOS GUI. Supporting that from teh Ardupilot OSDn_ITEM_ENABLE , OSDn_ITEM_X and OSDn_ITEM_Y would probably be troublesome.

At moment I can't see a benefit of using this way over the normal way but it is quite cool. If its just adding messages I would happy to look at that if can verify the general iNAV works

**Comment by SilentZen** [comment]
That is correct, Only some elements are supported.
https://forum.dji.com/thread-219321-1-1.html has a list

**Comment by ShikOfTheRa** [comment]
Pretty sure it will 95% work as it is today with no work. 

On OSD:
Flash standard iNav

On Ardu:

SERIALx_BAUD, 115
SERIALx_PROTOCOL = 33
OSD_TYPE = 3
MSP_OPTIONS = 0 (polling mode)

**Comment by SilentZen** [comment]
Thanks, Ill give it a test.

**Comment by SilentZen** [comment]
I actually meant could MSP output to DJI airunit using mwosd standalone unit. I understand it would be limited as there is only one tx and rx meaning GPS is not viable but other sensors ie. current sensor voltage and rssi can be used.
This is a prorject that outputs to dji airunit using MSP https://github.com/crashsalot/VOT_to_DJIFPV.
Sorry for the confusion I caused.

**Comment by ShikOfTheRa** [comment]
Ah understand now. I completely misunderstood.

It is feasible, but would need some time to test and develop so wouldn't be able to do this.
I would say it would be easiest to use a small cheap FC running betaflight or iNav. It should be ready to go.

**Comment by ShikOfTheRa** [comment]
I have added this to the development "wish list" :
https://github.com/ShikOfTheRa/scarab-osd/wiki/MWOSD-development-tracker

It is not planned since there is only one request, which is not enough to justify the time unfortunately.
