### ISSUE TITLE
BUG - CUSTOM field switches off

### ISSUE THREAD

**Issue by AaryanL** [ShikOfTheRa/scarab-osd-gui#11]
Here is the bug:

Flash FW
Settings: default
Go to TX-HIGH osd screen
Set CUSTOM to on
Press Write
When writing complete -  CUSTOM switch will toggle to Off by itself.

![Screenshot_2_cr](https://user-images.githubusercontent.com/84386055/154809723-10d27efb-7992-49cb-a670-032bb99ff690.jpg)

**Comment by AaryanL** [comment]
Hi!
Any news on fixing this?
Really uncomfortable problem for the constant use.
Thanks!

**Comment by error414** [comment]
I will look at it durring week

**Comment by AaryanL** [comment]
Hi!
I've downloaded the latest version of 2.0 and now CUSTOM field is not saving in TX-HIGH window AT ALL!

Honestly this is quite frustrating, because I put some necessary functionality there, and now I can't use it. This is not a cosmetic bug, would be really nice to have it fixed soon.

Thank you!

**Comment by ShikOfTheRa** [comment]
Hi - bug is confirmed. It fell of the radar. I will look at within next few days.

**Comment by ShikOfTheRa** [comment]
Hi Alex,

error414 has fixed! Can you test updated GUI?

https://github.com/ShikOfTheRa/scarab-osd-gui/raw/master/MW_OSD_GUI/R2.0/MWOSD-configurator-R2.0-win64.zip

**Comment by RM-FPV** [comment]
Hi Gary!
Yes it works properly now!
Thank you very much!

I'm still testing my remaining MAH meter ), but there were not many flights
this year because of many factors. Really naoughty weather, my favorite
spot was destroyed by turning into a new construction site, and some new
very unclear interference on video the reason for which I haven't found yet.

How are you? How are things going?

Regards
A.

**Comment by ShikOfTheRa** [comment]
Hi Alex, that is great. 

Sorry to hear about flying site. It is not good news. I also lost two. I do not have a good one close to me anymore :( 

Am good here - just life is too busy. I keep hoping one day it will become less busy but family needs a lot of my time.
I still get  a few flights but weather here has been hot. We are not used to it! It says 42 degrees today. Exactly double average!
