### ISSUE TITLE
Font editor Bug list

### ISSUE THREAD

**Issue by AaryanL** [ShikOfTheRa/scarab-osd-gui#12]
Here is a quick dirty list of some bugs I could remember after some font editing today:

1. Most annoying - no extension is added when saving a font.
2.  /not relevant/
3. Sometimes font files get corrupted on saving, some lower part symbols get shifted from their position. Very weird, happened a couple of times.
4. Left / Right buttons do nothing in the char editing window.

Other than that, the Font editor is absolutely brilliant!

**Comment by error414** [comment]
1) ok
2) I can't reproduce it, rewrite file works ok, what OS do you use? Win64?
3) never happend to me ;(. can you please attach corrupted file?
4) ok

https://www.dropbox.com/s/7dez3owixrppl35/MWOSD-configurator-R2.0.1-PRE-PRELEASE-win64.zip?dl=0 here is app, there are fixed 1 and 4. Maybe it fix 2 and 3 as well. :), Can you plase test it?

**Comment by AaryanL** [comment]
Hi!
Please have a look at the font. Last three lines are kind of moved down by one pixel compared to the default font that I used as an original.

As for #2 - I couldn't reproduce that myself anymore. It's win10. I've noticed twice that after editing one symbol it didn't change in a saved file. If it happens again I will report, but now I'm thinking that it could be my mistake, because I have too many files and some of them are without the extension. So I could just miss the correct file.  
I hope #1 will also fix #2 ).  

[my font 3.zip](https://github.com/ShikOfTheRa/scarab-osd-gui/files/8105328/my.font.3.zip)

**Comment by error414** [comment]
hmm, imposible to find what happened there. I would need original font, corrupted font and step by step editting what you did.

**Comment by AaryanL** [comment]
Original font is the default one from the GUI
I've changed almost 1/3 of the font and it was a very long term job, so it's impossible to tell when that has happened.

if you don't see any obvious reason why could it be - please wait until I will try to catch that moment again.
unfortunately I'm almost finished the font, so it might take some time )
compared to how many times I was saving fonts and their different versions, it's probably a very rare occasion in fact
thanks
