### ISSUE TITLE
GUI 2.0.0 show 2.0.0.0 as new version

### ISSUE THREAD

**Issue by sl1pkn07** [ShikOfTheRa/scarab-osd-gui#14]
![Screenshot_20230606_005619](https://github.com/ShikOfTheRa/scarab-osd-gui/assets/462213/e126e877-d9da-4598-a41e-51b94914c5dd)

**Comment by ShikOfTheRa** [comment]
Hopefully resolved! Thanks you

**Comment by sl1pkn07** [comment]
hi

yep. is solved. 

thanks!
