### ISSUE TITLE
GPS longitude label is wrong

### ISSUE THREAD

**Issue by khmewes** [ShikOfTheRa/scarab-osd-gui#2]
The overlay screen label says "lat" for the longitude label also, instead of "lon" on my video monitor. In the GUI app it shows correctly as lon. Is this a bug or an issue that just I have?

**Comment by khmewes** [comment]
After getting the GPS to work using the GPS OSD mode with 115200 baud and 4Hz update rate the correct label "Lon" appeared. So the display is "Lat" twice when there is no lock, i.e <6 satellites and a 0.0 display for both latitude and longitude. I additionally flashed with V. 1.9 from online to get rid of a 'Write Failed' error when I had written the firmware from Arduino tool. This worked at first i.e. no  write Failed error but showed up over time.  For the GUI configurator 1.9.0.1 flash I selected Version 1.9.0.0,  microminim, GPS-OSD and NMEA,protocol. I am using a BeStar BS-300 GPS module with a CIROCOMM 580 ceramic antenna (salvaged from a Walkera Scout X4).

**Comment by ShikOfTheRa** [comment]
On hols at moment. Back Monday and will have a look for you.

**Comment by khmewes** [comment]
Hi,

Hope your hols are great. Can you also give me some pointers on how to set up and connect a microminimOSD to a Walkera FC such as the Devo-M? They are APM compatible but lack a telemetry port  like the PIXhawk. They do have a databus.

 

Thanks.

**Comment by ShikOfTheRa** [comment]
ah - forgot this.

If still interested there is an updated version of the GUI and OSD firmware. Firmware available by clicking the show test option
