### ISSUE TITLE
Flashing the Firmware Programming Failed

### ISSUE THREAD

**Issue by mukhdi** [ShikOfTheRa/scarab-osd-gui#3]
Hi Shik

Im getting this message when trying to upgrade from R1.6 to the newest R1.9.0

# 2018-12-09 @ 11:10:04 -- Error: programing FAILED: Sending 3020: receiveData timeout after 400ms

What should I do

**Comment by error414** [comment]
Hello Mukhdi,

What OS do you use? Do you have selected right serial com port in GUI configurator. 
This is happening if GUI configurator doesn't receive any respond from device (bootloader). 

Can you attach you wiring schema and which OSD device you use.

**Comment by mukhdi** [comment]
Im using Win10 64bit with latest GUI
Im selecting port COM4 
Im using micro minimOSD with FTDI programmer ... the scheme would be

Dtx to dtx
Tx to Rx
Rx to Tx
5 volt wire
Ground wire

I could write and read the old R1.6 fw but when connecting to aircraft no overlay appeared but i can enter OSD menu with no problem ... so i decided to upgrade with the latest fw but no luck

**Comment by ShikOfTheRa** [comment]
Also make sure OSD not powered  up by any other pins at same time.

**Comment by mukhdi** [comment]
Im also using this arduino for flash 
1.8.6
1.8.3
1.0.6
1.0.5
1.0.4

The result is programming failed

**Comment by ShikOfTheRa** [comment]
Hi, when I have issue like this, I try to take back to basics.
Arduino board or OSD
Nothing else connected
All 6 pins connected straight through
Arduino set with correct com port / board set to Arduino pro or prom mini / 5v 16 Mhz 

Other things to try:
Check USB programmer is OK – some have a 3.3/5v jumper which needs to be set correctly. Also uninstall, reboot and re-install usb driver

**Comment by nickschaos81** [comment]
did this ever get resolved? I am currently having the same issue

**Comment by mukhdi** [comment]
Hi nickschaos81 ... try to remove tx pin ... dont use it ... just use rx pin only ... if still not working use the tx pin only remove the rx pin ... mine working with this method

**Comment by mukhdi** [comment]
Now my mmosd with GPS-OSD setup cant read sattelite ... any ideas

**Comment by nickschaos81** [comment]
will give it a shot right now

**Comment by nickschaos81** [comment]
so that fix did not work. tried both pins like you suggested.
Is it possibly a driver issue? where would i find the correct driver so i can check?

**Comment by mukhdi** [comment]
What programmer do you use, can you video it on youtube so maybe we can see it what maybe missed

**Comment by nickschaos81** [comment]
I can try

**Comment by nickschaos81** [comment]
mukhdi.... I... .am .... an idiot. Been way to long of a day. It helps if you have the osd plugged into the ftdi adapter correctly. I double and triple checked ... turns out I had it backwards. I just got a successful flash, lol
smh

**Comment by mukhdi** [comment]
Nice to know that ... happy flashing
