### ISSUE TITLE
Cannot purchase GUI

### ISSUE THREAD

**Issue by amagr0** [ShikOfTheRa/scarab-osd-gui#5]
Hello,

I'm trying for several day to buy the GUI for configuring MWOSD, but Paypal is not permitting doing this order.

There's another way that I can order the GUI?

Thanks

**Comment by ShikOfTheRa** [comment]
Hi,

it is a little awkward, alternative options via google here: (it is to purchase older version, but can transfer to pc app after). Same latest version - no difference.
https://chrome.google.com/webstore/detail/mwosd-configurator/jdfbjgomfcfpgkdjfnmekbkhkbgfminf?hl=en

cor an paypal direct to me at 
gary
at
flypix.co.uk

and I'll arrange

**Comment by amagr0** [comment]
Hello @ShikOfTheRa,

I bought from google, and already update it to 1.9.1.1.
Thanks
