### ISSUE TITLE
s there any other way to buy the registration code?

### ISSUE THREAD

**Issue by levin-wy** [ShikOfTheRa/scarab-osd-gui#6]
Hello, I can't buy the registration code on the website because the website can't display the verification code. Is there any other way to buy it?

**Comment by error414** [comment]
Hello, verification code is sent in email after receiving your payment. If you didn't received email please use form https://www.virtualpilot.co.uk/index.php?route=information/contact we will check it ASAP

**Comment by levin-wy** [comment]
I mean, I can't sign up for a website user, so I can't pay. Please see the screenshot





---Original---

**Comment by ShikOfTheRa** [comment]
Hello, I just tried to create account and it was Ok for me.

it is also still possible to buy configurator here:
https://chrome.google.com/webstore/detail/mwosd-configurator/jdfbjgomfcfpgkdjfnmekbkhkbgfminf

It will be older version, but It will give you a licence key for new version. It is same result in the end.
I hope maybe that helps

**Comment by levin-wy** [comment]
Thank you!



---Original---

**Comment by KenwoodFox** [comment]
The website is being a buggy mess right now. And that google webstore link is old, any new solution?
