### ISSUE TITLE
Can't write on the 1.9.1.1 config...

### ISSUE THREAD

**Issue by AeroStuffFPV** [ShikOfTheRa/scarab-osd-gui#7]
Hi! I have a major problem... I want to write my custom OSD screen to my minim osd (basic-no-gps) but I can't write it to the osd.

I bought the older version (1.7.1.9) and has the ''write'' button enabled but that version can't support the 1.9.1.1 so I can't do anything... It is really pissing me off. 

So how can I get the product key of the 1.9.1.1 configurator? Do I need to buy again or can the register (key) be sent to my email?

Regards,

AeroStuff FPV

**Comment by ShikOfTheRa** [comment]
Hi - mails sent - hopefully sorted!
